
app = "piratadecacau-wild-violet-8140"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_WEBHOOK = "https://piratadecacau.fly.dev/webhook/whatsapp-media"
  NODE_ENV = "production"
  WEBHOOK_TUNNEL_URL = "https://piratadecacau.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 5678
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "node /app/entrypoint.sh"
